### ISSUE TITLE
RTD does not build all pages

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/bcdamenu#6]
fails to import PyQt4.QtGui

perhaps can resolve using a virtualenv but need a requirements.txt file

**Comment by prjemian** [comment]
This is not working as contents of `requirements.txt`:

    versioneer==0.18
    qt>=4.8

**Comment by prjemian** [comment]
[RTD log](https://readthedocs.org/projects/bcdamenu/builds/5177826/) shows the reported error in context:

	Running Sphinx v1.5.3
	making output directory...
	loading translations [en]... done
	building [mo]: targets for 0 po files that are out of date
	building [readthedocs]: targets for 5 source files that are out of date
	updating environment: 5 added, 0 changed, 0 removed
	reading sources... [ 20%] index
	reading sources... [ 40%] install
	reading sources... [ 60%] license
	reading sources... [ 80%] settings
	reading sources... [100%] source_code/launcher

	../../README.rst:0: WARNING: nonlocal image URI found: https://img.shields.io/github/tag/BCDA-APS/bcdamenu.svg
	../../README.rst:0: WARNING: nonlocal image URI found: https://img.shields.io/github/release/BCDA-APS/bcdamenu.svg
	../../README.rst:0: WARNING: nonlocal image URI found: https://img.shields.io/pypi/v/bcdamenu.svg
	/home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/checkouts/latest/docs/source/source_code/launcher.rst:8: WARNING: autodoc: failed to import module u'bcdamenu.launcher'; the following exception was raised:
	Traceback (most recent call last):
	  File "/home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
		__import__(self.modname)
	  File "/home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/checkouts/latest/src/bcdamenu/launcher.py", line 11, in <module>
		from PyQt4.QtGui import *
	ImportError: No module named PyQt4.QtGui
	looking for now-outdated files... none found
	pickling environment... done
	checking consistency... done
	preparing documents... done
	writing output... [ 20%] index
	writing output... [ 40%] install
	writing output... [ 60%] license
	writing output... [ 80%] settings
	writing output... [100%] source_code/launcher

	generating indices... genindex
	writing additional pages... search
	copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
	done
	copying extra files... done
	dumping search index in English (code: en) ... done
	dumping object inventory... done
	build succeeded, 5 warnings.
	Copying readthedocs-dynamic-include.js_t... done
	Copying readthedocs-data.js_t... done
	Copying searchtools.js_t... done

**Comment by prjemian** [comment]
this might take longer to resolve and is not necessary once #5 is complete

**Comment by prjemian** [comment]
see https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by prjemian** [comment]
and maybe https://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by prjemian** [comment]
and here https://docs.readthedocs.io/en/latest/conda.html

**Comment by prjemian** [comment]
Current status: RTD build still [fails](https://readthedocs.org/projects/bcdamenu/builds/5201439/) but error is different now:

  File "/home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/conda/latest/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 465, in depart_bullet_list
	    self.compact_simple, self.compact_p = self.context.pop()
	ValueError: need more than 0 values to unpack

	Exception occurred:
	  File "/home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/conda/latest/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 465, in depart_bullet_list
	    self.compact_simple, self.compact_p = self.context.pop()
	ValueError: need more than 0 values to unpack
	The full traceback has been saved in /tmp/sphinx-err-VZsR0n.log, if you want to report the issue to the developers.
	Please also report this if it was a user error, so that a better error message can be provided next time.
	A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by prjemian** [comment]
setup a local conda environment to replicate the RTD build, per the build page:

	#!/bin/bash

	# on RTD
	#conda env create --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/checkouts/latest/environment.yml
	#conda install --yes --name latest sphinx==1.3.5 Pygments==2.1.1 docutils==0.12 mock pillow==3.0.0 sphinx_rtd_theme==0.1.7 alabaster>=0.7,<0.8,!=0.7.5
	#python /home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/conda/latest/bin/pip install -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/.cache/pip mkdocs==0.15.0 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext commonmark==0.5.4 recommonmark==0.1.1
	#conda env update --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/checkouts/latest/environment.yml
	#cat conf.py
	#python /home/docs/checkouts/readthedocs.org/user_builds/bcdamenu/conda/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html


	conda env create --name latest --file ./environment.yml
	source activate latest
	conda install --yes --name latest \
	   sphinx==1.3.5 Pygments==2.1.1 docutils==0.12 mock \
	   pillow==3.0.0 sphinx_rtd_theme==0.1.7 \
	   alabaster\>=0.7,\<0.8,\!=0.7.5
	pip install -U \
	   mkdocs==0.15.0 \
	   git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext \
	   commonmark==0.5.4 \
	   recommonmark==0.1.1
	conda env update --name latest --file ./environment.yml
	cd docs/source
	cat conf.py
	sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

**Comment by prjemian** [comment]
* configured eclipse to run that environment as a new interpreter
* built a python script to run the build locally:

``` python
   # simulate builds on RTD
    
    if __name__ == '__main__':
        import os
        import sys
        import sphinx
        
        options = '-T -E  -d _build/doctrees-readthedocs -D language=en . _build/html'
        
        sys.argv += options.split()
    
        os.chdir(os.path.join('docs', 'source'))
        sys.exit(sphinx.main())
```

**Comment by prjemian** [comment]
Confirm same error produced:


	  File "/home/prjemian/Apps/anaconda/envs/latest/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 465, in depart_bullet_list
	    self.compact_simple, self.compact_p = self.context.pop()
	ValueError: need more than 0 values to unpack

	Exception occurred:
	  File "/home/prjemian/Apps/anaconda/envs/latest/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 465, in depart_bullet_list
	    self.compact_simple, self.compact_p = self.context.pop()
	ValueError: need more than 0 values to unpack
	The full traceback has been saved in /tmp/sphinx-err-92fPIJ.log, if you want to report the issue to the developers.
	Please also report this if it was a user error, so that a better error message can be provided next time.
	A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

and setting breakpoint for debugger

**Comment by prjemian** [comment]
breakpoint debugging too tedious, error occurs while writing `index.html` file

start commenting out parts to locate point of error --> `README.rst` file

**Comment by prjemian** [comment]
It's the badges!

**Comment by prjemian** [comment]
Can't seem to option them out, it is because the images are not local and RTD's sphinx has problems with that.  Might take a GH issue to resolve that one.  Until then, it's either/or.  Could resolve this by either of these:

1. don't import `README.rst` in the `index.rst` (write all that content locally)
1. create a new `README.md` file

Let's go with the first one.
